### ISSUE TITLE
PDM Show Cars

### ISSUE THREAD

**Issue by Daemon53** [DSRP-Inc/DSRP_Tickets#10]
- Get rid of imports and customs from pdm show cars
- Super Category comes twice in pdm vehicle display list on the floor - didnt wanna test this change on a live server

**Comment by Daemon53** [comment]
Super Category comes twice in pdm vehicle display list on the floor - didnt wanna test this change on a live server

**Comment by PINCH97** [comment]
Resolved Super category showing twice

**Comment by ssarahkathleeen** [comment]
![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/141734142/e7adc91c-8d8d-46cf-9114-ca748ee9e2ef)

Super is still in here twice, the 'Super' one has only one car in it the Ignus
the 'super' in all lower case has the most cars

Also, I think the 'swap car' option isn't working on all cars

**Comment by ssarahkathleeen** [comment]
wait maybe it's when you are looking at from a certain spot you can see it

**Comment by ssarahkathleeen** [comment]
![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/141734142/80c1a66b-eb54-444b-87a6-b1b45a61c5ae)

far car on the left, 'swap cars' from any angle but the alt-eye menu does show up
car on the right can only 'swap cars' from one side of the car but the alt-eye menu shows up on both

**Comment by Daemon53** [comment]
Removed the extra super and adjusted text with capitals and spaces

![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/5520538/35d65cde-5c19-40f9-8584-7b9443e656ad)

**Comment by Daemon53** [comment]
@ssarahkathleeen Both of those cars allowed me to third eye all the way around.

**Comment by shelby0341** [comment]
can confirm only one "super" category, i didn't see any custom vehicles, i was able to change any car on the floor. moving to completed
