### ISSUE TITLE
Vending Machine Pricing

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#110]
**Reference ticket number:**

**Reporting persons Discord name:**
shelby0341

**Clearly describe the bug:**
Vending machine pricing is significantly higher than the gas station.
(Also I love how homie working at 24/7 is just smoking a joint on the clock inside...KEKW)

**Describe the steps to reproduce:**
Any vending machines

**What is the expected behavior?**
Be somewhat the same or the same

**Screenshots/clips:**
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/eeff1e70-1120-4e43-87c0-614758b04250)
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/1d5c6a27-8a45-4ab6-a8ca-d8c5a9cd9399)

**Comment by IngleArf** [comment]
changed pricing in config
