### ISSUE TITLE
311 and 911 Commands

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#112]
**Reference ticket number:**

**Reporting persons Discord name:**
shelby0341

**Clearly describe the bug:**
When people use the /911e command, EMS cannot respond to it via the MDT like they can when people use the /311 and /311a commands.

**Describe the steps to reproduce:**
Try responding to call via MDT

**What is the expected behavior?**
We should get rid of the /311 commands and utilize /911e, but have EMS able to respond to the calls via MDT like we could with the /311 commands.

**Screenshots/clips:**

**Comment by shelby0341** [comment]
When you use /911e or /911ea, the MDT shows it as a "311 Incoming Call" but works as intended and able to respond to both /911e and /911ea calls (are working as intended, thank you!)
![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/862c6cd6-e0d8-419d-a22f-cb5a1ba814c3)


/311 and /311a are both still listed when you start typing, but do not function (we don't want them to function, but they can be removed from the list)
![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/d5fa583e-ab72-466f-a8ee-d60e08e690a7)


A couple small changes for uniformity for the commands to read as follows:
/911e [message]
Send a message to the EMS.

/911ea [message]
Send a message to the EMS anonymously.
![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/67108ce1-9be5-488e-a2f5-796375ee6bcc)

**Comment by Daemon53** [comment]
How embarrassing...
@shelby0341 Back to testing

**Comment by shelby0341** [comment]
looks like everything is working as intended, pinging correctly, able to respond to calls, 311 is removed, looks good thank you! moving to completed
