### ISSUE TITLE
Split inventory shipments for businesses

### ISSUE THREAD

**Issue by Daemon53** [DSRP-Inc/DSRP_Tickets#113]

**Comment by Daemon53** [comment]
Verify teapot and and pond received two boxes of different ingredients when ordering.

**Comment by shelby0341** [comment]
can confirm both places receive two boxes...however...
pond cafe - you cannot order ingredients without enough cash in the business account
little teapot - you can still order ingredients with $0 in the business account

**Comment by Daemon53** [comment]
fixed amount check

**Comment by shelby0341** [comment]
can confirm is working as intended now "Funds are looking a little low buddy." moving to completed
