### ISSUE TITLE
Pillbox Outfits - can't create new outfits

### ISSUE THREAD

**Issue by ssarahkathleeen** [DSRP-Inc/DSRP_Tickets#116]
![Image](https://user-images.githubusercontent.com/141734142/260872771-2bc8a61d-8c17-4d82-b8c5-98078bf7b029.png)

Can't create new outfits, can only change from outfits already saved

**Comment by Daemon53** [comment]
This was intended. Making it able to go shopping and buy clothes puts a blip on the map due to encrypted code (and doesn't make as much sense as just changing your outfit)

**Comment by ssarahkathleeen** [comment]
Ah okay, just makes it annoying when we hire new staff we can't take them in to create outfits we will have to take them to clothing store.
Unless that's what the code thing is for? Although that does not allow them much individuality.

**Comment by Daemon53** [comment]
Our hands are tied with this one. You can set the codes and then they could maybe change it up a bit on their own time?
