### ISSUE TITLE
PD 10 Codes Need to be updated

### ISSUE THREAD

**Issue by kschreck0105** [DSRP-Inc/DSRP_Tickets#120]
**Reference ticket number:**

**Reporting persons Discord name:**

**Clearly describe the bug:**
The 10-Code that comes up for dispatch needs to be updated in the config file. 

**Describe the steps to reproduce:**

**What is the expected behavior?**

**Screenshots/clips:**

**Comment by Daemon53** [comment]
@kschreck0105 If you just want to point me to the doc where they are, I'll update it.

**Comment by kschreck0105** [comment]
you saw nothing

**Comment by Daemon53** [comment]
I think weapon classes is a separate issue. Special coding for that

**Comment by Daemon53** [comment]
This was just the 10 codes

**Comment by kschreck0105** [comment]
wrong copy paste... lol

**Comment by Daemon53** [comment]
We good here?

**Comment by kschreck0105** [comment]
From what i have seen yes
