### ISSUE TITLE
Emote misspelled on multicharacter screen

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#129]
when you load in to the server, my character was assigned the "crossarms5" emote to do, but it's misspelled so it gave me a Help error prompt

![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/37c67350-d4eb-4f84-b9d4-c57b8be73eae)

**Comment by IngleArf** [comment]
resolved and added a couple more emotes to the table 
double checked spelling too lol
