### ISSUE TITLE
PD Evidence Bags not showing whats properly in the bag

### ISSUE THREAD

**Issue by kschreck0105** [DSRP-Inc/DSRP_Tickets#13]
**Reference ticket number:**

**Reporting persons Discord name:**
Rogie205

**Clearly describe the bug:**
When bagging evidence (a gun) it doesnt show the correct weapon in it. and when you move it around your inventory it changes the description to something nearby the filled evidence bag. 
In picture 1 it should say PD M4A1 not raypistol. 
In Picure 2 i moved it and it changed in my inventory.

Picture 3 when i "use" the bag it shows the proper item in the bag.

**Describe the steps to reproduce:**
Get gun. use command /bagev and put gun in bag. move around inventory to see what it does. 

**What is the expected behavior?**
after i bag the evidence it should say the correct gun in the bag and stay that way when moved around the inventory

**Screenshots/clips:**
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/68434249/ffba9052-124e-4fb3-bae8-4966be22c319)
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/68434249/c3c273d1-ad23-4b70-adf8-a75a62170c2d)
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/68434249/8496caf7-a042-43c3-a720-de563d6636b1)

**Comment by Daemon53** [comment]
Casings, Fingerprint read outs, Fingerprints, and blood work.

Weapons and drug tests don't show correct info, but when used they do.

GSR tests don't show correct info when hovered or used.

**Comment by Daemon53** [comment]
StoreRob fingerprint drop reminder

**Comment by Daemon53** [comment]
https://regalonefour.github.io/category/8-setting-up-subsystems/

**Comment by Daemon53** [comment]
Check caliber for XM3, Uzi, MAC-10,

**Comment by kschreck0105** [comment]
GSR Seems to show correct when hovering over but not when used.

**Comment by Daemon53** [comment]
I couldn't see any menu function for a GSR test. Not sure it has one.

**Comment by kschreck0105** [comment]
i mean all we really need it to say if its positive...

**Comment by Daemon53** [comment]
like it does on the hover? or more than that? more than just he hover?

**Comment by kschreck0105** [comment]
![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/68434249/94650a92-900f-4573-83e2-97c5c9789e44)

This when hovering

**Comment by kschreck0105** [comment]
When moving PD Evidence bags around inventory. it still shows what is in the bag and doesnt change as seen above when moved around
