### ISSUE TITLE
EMS Benny's Option

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#131]
Is it possible to get the "interior color" to default to the Standard "Blue" for all EMS vehicles? On several of the vehicle liveries, the call sign and the "Supervisor / Command" signs are defaulted to white and they blend in to the Pillbox livery.

![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/e6a0db35-f199-4067-bca4-55f6bcb01051)

**Comment by IngleArf** [comment]
added working
