### ISSUE TITLE
Cannot Load Hunting Rifle

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#132]
Cannot load ammo into the hunting rifle from the hunting store

**Comment by shelby0341** [comment]
It shows it takes it from your inventory, but it doesn't. No F8 errors

![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/4e200411-8ec3-4703-b9f9-574957488aa8)

**Comment by IngleArf** [comment]
Just fixed and tested. Plz double check and test because apparently the hunting rifle likes to break for 0 reason lol

**Comment by shelby0341** [comment]
I was able to load it as well, moving to completed
