### ISSUE TITLE
EMS Benny's Issue

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#133]
You can use the Benny's menu in Pillbox garage to repair and customize player-owned and local vehicles if you have the EMS job for free.

**Comment by IngleArf** [comment]
Restricted vehicles able to use Benny's to just "emergency" vehicles (class 18). Tested with 1 vehicle from EMS at pillbox and one at PD. Both seemed to work. Could not use personal vehicle at either Bennys

**Comment by shelby0341** [comment]
Tested EMS Benny's and is working as intended, cannot customize local or player owned vehicles but can still customize EMS vehicles. moving to completed
