### ISSUE TITLE
GSR Testing in PD Evidence Script issue

### ISSUE THREAD

**Issue by kschreck0105** [DSRP-Inc/DSRP_Tickets#14]
**Reference ticket number:**

**Reporting persons Discord name:**
Rogue205

**Clearly describe the bug:**
when investigating someone it says they "Smells of gunpowder" but doesnt give a postive result in the gunpowder test.

**Describe the steps to reproduce:**
get gunshots to be near you until you see the notification you "Smell of gunpowder" and then get a gsr test done on you.

**What is the expected behavior?**
when someone smells of gunpowder it should return a positive on the test through the script. 

**Screenshots/clips:**
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/68434249/11535d2a-9e5b-4dbc-8708-0b7417d82f29)
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/68434249/fcf9a7a0-cb23-4f4a-a74b-0eae87de8812)

**Comment by Daemon53** [comment]
This seems to work now but the evidence bag is messed up for it. See PD Evidence issue

**Comment by kschreck0105** [comment]
was able to investigate and ":smell" gunpowder. was able to get the positive test as well

![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/68434249/31378d9e-7299-49eb-8629-91428c4e3c5e)


![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/68434249/b039a77a-a475-4781-a10b-909b3436a664)
