### ISSUE TITLE
Bank Trucks?

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#143]
After 4 tries of doing it, it tells me to go to the same phone. Not sure if this is intended or if it should be randomized which phone it pings? Tried to start it at different times of day and same results.

**Comment by Daemon53** [comment]
Sure that is the right pay phone? That is the prompt you get for any pay phone. The one you get for the job is different.

**Comment by shelby0341** [comment]
This is where "Destination" is on my GPS, I tried the next payphone but it gave the same thing and isn't close to this one
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/8dac0804-596f-4e8d-a681-55790cc6acad)

This is the next phone over, tried it and same thing. There's no pay phones to the West of it
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/eb151812-6dab-4e11-99b4-bdd44282ea08)

**Comment by shelby0341** [comment]
Can confirm it is randomized now, the only thing I'm not sure if it can be changed or not is the part if you open the option to call the person and cancel it without even calling anyone...it gets rid of the option to call someone altogether and you lose your item from the first part.

**Comment by shelby0341** [comment]
Can confirm it is randomized, moving to completed
