### ISSUE TITLE
Bennys in PD Garage not Repairing car.

### ISSUE THREAD

**Issue by kschreck0105** [DSRP-Inc/DSRP_Tickets#147]
**Reference ticket number:**

**Reporting persons Discord name:**
Rogue

**Clearly describe the bug:**
Bennys in PD garage not repairing vehilce **functionality** only **visual** aspects of the car

**Describe the steps to reproduce:**
get vehicle.... break vehicle, take to bennys in PD Garage and use the repair

**What is the expected behavior?**
full engine/function and visual repair.

**Screenshots/clips:**

**Comment by kschreck0105** [comment]
Doesnt not repair for EMS either.

**Comment by IngleArf** [comment]
this is ready for testing agian

**Comment by kschreck0105** [comment]
both EMS and PD car appear to be repairing as expected. 

Closing this and moving on
