### ISSUE TITLE
Spelling/Grammar Police Checking In

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#148]
**At the Leisure Store:**
coldweiner > Cold Weiner
hotdogbun > Hot Dog Bun
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/e17f58c6-2eee-411f-b436-d2a49b4f9540)

**On the character selection screen:**
avaible slots > available slots
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/75e5f754-40be-4103-9ff3-a39cfb4c91b4)

**Gardening job:**
Good Morning Sir > Good Morning
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/1ee19f8c-e01f-4d80-ac18-86c2b114f65c)

You pulling out the leaf blower... > You're pulling out the leaf blower...
--It is this prompt for all the items you get from the back of the van
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/633f96c2-9c82-4d8f-ba5d-41933503a60c)

You putting tool into trunk... > You're putting tool into trunk...
--It is this prompt for all the items you return to the back of the van
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/e9accbd4-f8f8-4c8e-817f-2bf48df30427)

**Comment by IngleArf** [comment]
spelling issues corrected

**Comment by shelby0341** [comment]
@IngleArf One more - in the construction job you get a prompt when you finish that says "You have earned 150$ and X experience. Totally experience [X]"
-> "You have earned $150 and X experience. Total experience [X]"


![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/cc0431af-4199-4669-80c3-fc658372f966)

**Comment by IngleArf** [comment]
This has been changed
