### ISSUE TITLE
randomly dying while diving

### ISSUE THREAD

**Issue by ssarahkathleeen** [DSRP-Inc/DSRP_Tickets#159]
not sure if the diving has a time limit, but after maybe... 5-10 minutes of dying I randomly died
It happened 2-3 times before I did this ticket because I wanted to make sure it wasn't just user error

But I think potentially the driving gear might have a time limit, and since there is no way to buy oxygen tanks I definitely think the time limit needs to be extended, or a warning to get to the surface needs to appear or something

**Comment by IngleArf** [comment]
amended item description to the following:

This is a  Rebreather system, dont forget to come up for air ;)
