### ISSUE TITLE
Little Teapot Hot Food Emote Issue

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#16]
**Reference ticket number:**

**Reporting persons Discord name:**
shelby0341

**Clearly describe the bug:**
When working at Little Teapot and you make anything in the "Hot Food" section (breakfast bagel sandwich, avocado toast, eggs benedict or grilled cheese), as a female, you get the notification about "This emote is male only, sorry!" and you just stand there doing nothing. It's an issue with the grilling emote.

**Describe the steps to reproduce:**
Try to make "Hot Food" at Little Teapot as a female character.

**What is the expected behavior?**
You should do some sort of emote, the grilling emote is wonky with females though.

**Screenshots/clips:**

**Comment by IngleArf** [comment]
tested and working, reaplced bbq with bbqf, turns out bbqf is unisex lol
