### ISSUE TITLE
Little Teapot Food Prep Station Menu Bug

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#17]
**Reference ticket number:**

**Reporting persons Discord name:**
shelby0341

**Clearly describe the bug:**
When you're in the Little Teapot at the "Food Prep Station", and you make the egg sandwich, butter croissant, peanut butter and jelly or salmon bagel, once you're finished, it opens up the "Hot Food" menu instead of the Food Prep Station menu.

**Describe the steps to reproduce:**
Make an egg sandwich at Little Teapot

**What is the expected behavior?**
You should make the egg sandwich, butter croissant, peanut butter and jelly or salmon bagel at the food prep station, then the food prep station menu should pop back up, NOT the hot food menu.

**Screenshots/clips:**

**Comment by IngleArf** [comment]
This bug has been fixed and is ready to be tested

**Comment by shelby0341** [comment]
Tested all items listed and all work as intended, thank you!
