### ISSUE TITLE
MDT Weapons Tab issue

### ISSUE THREAD

**Issue by kschreck0105** [DSRP-Inc/DSRP_Tickets#18]
**Reference ticket number:**

**Reporting persons Discord name:**
Rogue205

**Clearly describe the bug:**
If I spawn in a weapon, it will be registered to the weapons tab and can be looked up 

**Describe the steps to reproduce:**
spawn weapon and review the weapons tab in PD MDT

**What is the expected behavior?**
Probably shouldnt be registered... lol

**Screenshots/clips:**
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/68434249/2c424a90-b1aa-4f60-a886-d5ed508d05be)

**Comment by Daemon53** [comment]
@kschreck0105 
Now configured to register weapons bought at AmmuNation and Hunting shop (this is including knives). PD armories also register but say "Police Issued". @shelby0341 EMS armories also register but say "Hospital Issued". Spawned items do not go into MDT.

Class will always display as 1 right now. If you want that changed @kschreck0105, I'll need you to take weapons from the items list and give me classes for them.

Need to double check crim activities that these don't register weapons. Checked that bobcat does not register and it gives unserialized weapons.

**Comment by kschreck0105** [comment]
Can confirm spawned weapons do not get registered

**Comment by kschreck0105** [comment]
still want to keep open to check other crim activities

**Comment by Daemon53** [comment]
I'll test one other place where they might be. Just get me the class list when you can. @kschreck0105
