### ISSUE TITLE
Little Teapot Ham & Cheese Croissant Issue

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#19]
**Reference ticket number:**

**Reporting persons Discord name:**
shelby0341

**Clearly describe the bug:**
At Little Teapot, when you make the "Ham and Cheese Croissant", it'll take the ingredients from your inventory, shows that you received the item but you do not.
Also, after you attempt to make the ham and cheese croissant, you can no longer open you inventory or any stash until you relog.

**Describe the steps to reproduce:**
Attempt to make a ham and cheese croissant at Little Teapot at the Food Prep Station

**What is the expected behavior?**
You should get the ham and cheese croissant in your inventory once you make it.
You should also be able to open your inventory and look in any stashes or on the ground after making this without having to log out and back in.

**Screenshots/clips:**
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/5fb0bccd-6a23-499f-8d74-04aefefb4b1f)

**Comment by shelby0341** [comment]
*Adding that there is no F8 errors either.

**Comment by IngleArf** [comment]
will have to wait until next restart, the issue likely was the the item "name" column was missing the "r" in croissant

**Comment by IngleArf** [comment]
Tested and working
