### ISSUE TITLE
PD Car Handling

### ISSUE THREAD

**Issue by Daemon53** [DSRP-Inc/DSRP_Tickets#190]
21 Tahoe- turning- low speed turning/ accel turning
Cvpi a bit heavier, takes flight on curbs, other aspects good
Camaro- everything sadly
Polchallenger- acceleration a tad, or lower wheelslip off start. 
Durango- overall tuning turning/accel
gt4rs - braking added, turning adjusted at speed
Mustang- swap to rear wheel drive, overall good tune
Trx- lower accel, adjust turning and braking a lot of love
Tahoe- turning adjustments while braking and accel
Corvette- converted to rwd
Raptor same as Trx plus better brakes
14 charger- a bit heavier to avoid going airborne on curbs

**Comment by kschreck0105** [comment]
closing this out!
