### ISSUE TITLE
Two Race Harness Recipes

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#20]
**Reference ticket number:**

**Reporting persons Discord name:**
shelby0341

**Clearly describe the bug:**
The race harness is listed in both the "mechanics tools" and the "cosmetics items" with different recipes.

**Describe the steps to reproduce:**
Look at "mechanics tools" and "cosmetic items" recipes in mechanic shop

**What is the expected behavior?**
One or the other should be picked, probably get rid of the cosmetic one since being in mechanic tools makes more sense.

**Screenshots/clips:**

**Comment by IngleArf** [comment]
removed the recipe that did not require nylon rolls in the cosmetics section

**Comment by IngleArf** [comment]
removed cosmetics harness and kept the one in tools section as intended ty
