### ISSUE TITLE
Washing Rocks Item Dupe

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#202]
Reference Discord ticket 0048 submitted by SeeTheGoombas:
"washing rocks if you save machine and then cancel it dupes them"

https://medal.tv/games/gta-v/clips/1twUbCZ4jZvjgS/d1337KGpvgLp?invite=cr-MSx5dUYsNDk0MjQ4MzIs

**Comment by Daemon53** [comment]
I cannot reproduce this bug

**Comment by shelby0341** [comment]
Moving to testing to try and replicate again

**Comment by shelby0341** [comment]
Going to close, I still can't replicate this
