### ISSUE TITLE
Pillbox "Layin Bed" 

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#21]
**Reference ticket number:**
0010

**Reporting persons Discord name:**
yakiboi

**Clearly describe the bug:**
When you go in to Pillbox, you can third eye the beds in the Ward A Intense Care room to "Layin Bed" (Lay In Bed) and it charges you $2,000

**Describe the steps to reproduce:**
Third eye the beds in Pillbox, "Layin Bed"

**What is the expected behavior?**
I feel like this should be removed all together, it's weird to me that you would just go to a hospital, not check in, and lay in the bed.

**Screenshots/clips:**

**Comment by IngleArf** [comment]
i think is actually on a mental checklist so ty for adding it!

**Comment by ssarahkathleeen** [comment]
confirmed, this still happens

**Comment by ssarahkathleeen** [comment]
Checking in works, moves you to a bed.
But I think you shouldn't be able to run in and 'lie' on the bed.

Also 2k is a bit steep, is that going to be the price when EMS is offline? I know we were discussing charging people less for good medical RP

**Comment by ssarahkathleeen** [comment]
Tested this now, seems to be fixed
When you alt-eye the beds there is no option to lie in the bed

**Comment by ssarahkathleeen** [comment]
With check-in costs, can we make it different prices depending if there are doctors online or not?

**Comment by Daemon53** [comment]
If you want to make a new issue with suggested scenarios and prices, we can review it. If the beds are fixed, you can move this to done.

**Comment by shelby0341** [comment]
@Daemon53 so sorry...but it was brought up to me in something I didn't think of, that being able to third eye a bed/xray bed should be a thing people are able to do but not get charged, and do not get any healing from it. This will allow a doctor to get a patient from the lobby, take them to a room and they can third eye the bed or x-ray machine or similar, to lay on it while getting treatment instead of being pushed all around and in weird positions falling through the bed etc, when you just emote lay down on it.

**Comment by Daemon53** [comment]
@shelby0341 
I'll put that part back in (minus the heals). The other beds will have to be a later enhancement.

**Comment by Daemon53** [comment]
@shelby0341 Back to testing

**Comment by shelby0341** [comment]
works as intended, able to lay in the bed via third eye without gaining health and not charging money, thank you! moving to closed
