### ISSUE TITLE
Duplicate License Plates

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#212]
The issue regarding duplicate license plates needs to be looked in to and addressed. The issue being that a local car can spawn with the same license plate as a players license plate leading to the wrong car being impounded, and the fact that a player can keep their belongings in their car trunk and it would be accessible to the duplicated local car - thus being stolen.

**Comment by shelby0341** [comment]
Possible fix - adding "DSRP" in front of local license plates

**Comment by shelby0341** [comment]
![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/41261a78-589f-48af-90fd-f2eeb201c60c)

**Comment by IngleArf** [comment]
it seems it is going to be easier to have player cars bought through PDM and rental cars start with DS or simply  P for player,

will have to experiment on dev server in the following way

have cars with items in gloves and trunks stored in garages that belong to several test players
Change configuration of player bought cars in vehicleshop script, and change everyones plate to have a P in it
Test the cars that existed and got their plates changes and make sure nothing is missing from them

If all goes well, we can push the vehicleshop change, and then go through the playervehicles table in the database and change all existing vehicles in the live server


@Daemon53 thoughts?

**Comment by Daemon53** [comment]
@IngleArf
Actively working on this. Shelby is confirming local cars plate format for me in the server now. We can't make a static letter like P be the first letter of every player plate with our current vehicleshop script. With this test I'll confirm, but I'm guessing spaces in the plates will be our best option.

Once we have this, yes, we'll have to change everyone's plates in multiple tables in the DB so we have to make sure each table syncs together.

**Comment by Daemon53** [comment]
UPDATE my_table
SET my_column = CONCAT(SUBSTRING(my_column, 1, 3), ' ', SUBSTRING(my_column, 5));
