### ISSUE TITLE
Tattoo Shop Issues - Possible Update?

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#215]
If you "apply" a tattoo and "save" a tattoo - it takes $750 from you twice
It also randomly removes some tattoos if you preview a tattoo, so if you apply a new one with a few removed, it'll save with those removed. If you back out of the menu it seems to fix it if you try to preview it again.

**Comment by Daemon53** [comment]
I believe they are only getting charged once now and not on save.

As far as how the rest of that menu is working, I'm not sure we want to mess with that too much as that is tied to ped creation and clothing too.
