### ISSUE TITLE
Courier Locals

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#219]
The local peds start to stack up from courier job
Will spawn in the roads as well
Someone also stated "if you bump into them sometimes theyll run away and when you are finished handing in the box, they will stop running and hold their hands out like they have a box."

**Comment by Daemon53** [comment]
PEDs are being spawned on everyone’s client but only deleted from the original players client.

**Comment by shelby0341** [comment]
can confirm welcoming committee's are no longer there
