### ISSUE TITLE
LSC Car Washing Station?

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#220]
We were wondering if it would be possible to add a car washing station at LS Customs? The long term plan would be to sell repair kits and cleaning kits at the storefront, but able to offer free car washes with repairs/upgrades (similar to the stand up car wash podiums at some gas stations). Idk if it would make sense to maybe go between the two paint bays? Most people are using that bay door anyways as In and Out, theoretically there would be drains all over a shop for fluids. Unless you have a better idea aside from it going across the parking lot? I didn't want it to be in the way of our tow drivers if it went outside. Not sure if it could be linked to the job where only mechanics could third eye it to use it?

![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/741199a0-1f19-41c4-8381-1ae45491052e)
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/0c631760-882b-4f33-9498-d2edc0573b98)

**Comment by PINCH97** [comment]
Added
