### ISSUE TITLE
Chop cars spawning with low/no fuel

### ISSUE THREAD

**Issue by ssarahkathleeen** [DSRP-Inc/DSRP_Tickets#222]
'Sometimes you get chop cars with almost empty fuel red gaudge and have to take from cit to sandy'

Sounds like the same issue that was happening with the courier trucks

**Comment by shelby0341** [comment]
i haven't seen anyone comment, or personally seen, any 'no' fuel cars anymore.

some locals park their cars with low fuel, adding the ability to fuel in small increments instead of 'all or nothing' should help with low fuel. going to close this for now as the fuel is a separate ticket
