### ISSUE TITLE
Putting House Robbery Items in Vehicle Trunk Issue

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#230]
Discord tickets:
https://discord.com/channels/975465175178153994/1150689592983433267
https://discord.com/channels/975465175178153994/1151412334846291978

Seems there is an issue putting items in trunks that you get from house robberies. I understand you have to be centered to the trunk but there's a clip in the second ticket there showing they were pretty centered and it still didn't work. They tried several vehicles and same result. Gives error "You need to be near a trunk!"
Maybe the area can be expanded a bit that recognizes the trunk? Not sure how the scripting works.

**Comment by Daemon53** [comment]
@IngleArf Have never looked at this so I don’t know if it is locked or not. Do they get an item when they steal it? Does the item actually go in the trunk? We could do something similar to oxy where it loops to see if the item is in their pocket and if so, it forces them to do the carry emote, maybe? This way they just have to put things in their inventory and then move the item from their inventory to the trunk?

**Comment by IngleArf** [comment]
So in the clip of him trying to put it in the trunk...I've had that happen. But you gotta be centered on the trunk and not running around like that. If he would have maybe moved left a little it would have worked...I gotta go into the dev environment to check. But yea. You just gotta sit at the center rear trunk and not just run by it spamming E. 

But the way it works is there are certain props they have to third eye. Once they have it it's in their hands and they can't do anything until they either drop or put it in trunk

**Comment by IngleArf** [comment]
BUT there is a house robbery script update that I'm gonna try tomorrow. I can't find patch notes anywhere but it's worth a shot. 

Script is locked but don't remember how badly. Could try making the trunk distance check bigger?
