### ISSUE TITLE
Big Bank ATM's Not Working

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#231]
Discord ticket: https://discord.com/channels/975465175178153994/1150689592983433267

When you try to use the ATM's at the big bank lobby in Vinewood area, your bank pin turns red and it rejects it. It works elsewhere though.

**Comment by shelby0341** [comment]
These were disabled in the 9/17 changelogs. Not sure if we wanted to leave this open to try to get them working?

**Comment by IngleArf** [comment]
Fixed, added polyzones for atm's as gabz pacific hates calling stuff in on those ATM machines themselves
