### ISSUE TITLE
Unable to tow other vehicles

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#233]
Currently, you cannot tow any local cars or player cars. You can only tow the car that is being demanded of for the tow job. So if a players car breaks down, we cannot go out to retrieve it to bring it to a shop.
It's like this on the slam tow truck and the regular tow trucks. The only one that seems to work is the older one with the hook on the back that we aren't supposed to have anyways.

**Comment by Daemon53** [comment]
Any update on this one? Did we try getting in the tow truck?

**Comment by shelby0341** [comment]
Silas was able to tow various local cars today...except for police vehicles for some reason it took a few tries to get it on or get it off the tow truck and looked different in different peoples eyes apparently. Something I'll have to test.
