### ISSUE TITLE
Teapot Issues

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#241]
Coffee: doesn't take anything after making but can only make one cup
Chai latte: can't make
Hot chocolate: cant make (makes flat whites?)
Latte: didn't take coffee beans after making
Macchiato: didn't take coffee beans after making
Mocha: didn't take coffee beans and one bar of coco after making
PB&J: does not take PB after making
Avocado toast: does not take vinegar after making

**Comment by IngleArf** [comment]
coffee fixed and tested
chai latte fixed and tested
hot chocolate fixed and tested
latte fixed and tested
macchiato fixed and tested
pb and j fixed and tested
avocado toast fixed and tested
