### ISSUE TITLE
Changing Teapot & Pond To Buy Individual Ingredients?

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#242]
Is there a way to change Teapot and Pond Cafe to be able to buy individual ingredients for now? They are struggling with some ingredients being used way more than others, then having to spend a whole $5k out of their own pocket for the few ingredients they need, and are unable to access the business funds so it's coming from their own pocket.
Maybe using the 24/7 convenience store script so it operates in that fashion?

**Comment by IngleArf** [comment]
Can we ask them to make a list of what ingredients they are using more than other so i can fix their distributtion system like i did pond cafe please

In the mean time i can make an "invenstment" to cover development time

**Comment by IngleArf** [comment]
i have buffed ingredients from both boxes they get to 50 as a stop gap

**Comment by shelby0341** [comment]
@IngleArf are we all set with this ticket to move to complete?

**Comment by IngleArf** [comment]
yes seems to be all good
