### ISSUE TITLE
LSC Work Area Into Parking Lot

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#243]
I know @IngleArf you were saying the work area to be able to work on cars stretched into the entire parking lot, but it actually just stops at the bay doors, so we can't repair anything outside. If we could be able to repair things in the parking lot that would be nice, thank you!

**Comment by IngleArf** [comment]
Yea I can take a look. That's weird. I could have sworn it stretched that far. Thx for letting me know

**Comment by shelby0341** [comment]
Marking as complete
