### ISSUE TITLE
Hotel stay extension, add a couple options?

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#248]
Can we add 1-2 day extensions to the hotel "extend day"? Currently you can only select 7, 15, or 30 days

![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/18a97552-3ee1-4739-8be0-389cc6ea9626)

**Comment by Daemon53** [comment]
No, unfortunately, that code is locked and we won't be able to change it.
