### ISSUE TITLE
Jerry Cans

### ISSUE THREAD

**Issue by Daemon53** [DSRP-Inc/DSRP_Tickets#28]
JERRY CANS SAYING EMPTY WHEN THEY SHOULD BE FULL (you buy a jerry can, fill it, and it seems when you get in the car or take it back out it doesnt register as being full.  Only when its been in your hand the whole time)

**Comment by shelby0341** [comment]
Seems to be working as intended now. Bought a jerrycan, filled it with gas, moved it from inventory to trunk, back to inventory, in and out of hands, got in the car with it in my hands and pulled it back out and still registered as full. Filled up a tank and got it down to 26/100 "ammo" (in the top right) and it kept showing as 26. Going to move this to finished.
