### ISSUE TITLE
Mechanic Script Eating Parts

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#283]
Sometimes if you install cosmetics or performance upgrades on vehicles, it takes it from your pocket, you "successfully" install it, but you look at the vehicle right after with the toolbox, and the part isn't installed.
This has happened to me in another server though that used the same script and it was never fixed, not sure if there's a fix out there or not?

**Comment by IngleArf** [comment]
this script has released a new version, it is a complete rewrite and there have been daily hotfixes to it

i am waiting for the hotfixes to subside before i test it. however, when it is ready, it will replace a lot of scripts that we use separately AND include some new goodies for mech shops.
