### ISSUE TITLE
Able to hit stores with just 1 cop on duty?

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#285]
It's being reported to me via dm that people were hitting stores with 1 cop on duty. Inglearf confirmed it's set to 2 and couldn't replicate in dev server. This should be further tested with more people?

**Comment by PINCH97** [comment]
It was actually set to 0 changed back to 2 and tested on dev server, pushed a hotfix to the main server as others will be able to hit them without cops around.

**Comment by IngleArf** [comment]
set myself to police on duty as the only person in the server and can not rob a store without having more police on duty. moving to done for now

**Comment by IngleArf** [comment]
config matches on main live server code, closing issue
