### ISSUE TITLE
PD Armory

### ISSUE THREAD

**Issue by Daemon53** [DSRP-Inc/DSRP_Tickets#29]
PD Armory giving random items

**Comment by Daemon53** [comment]
Another one of those "wtf". I've never had this issue with it. @kschreck0105

**Comment by IngleArf** [comment]
Tested taking out items at the same exact time as Aladrex from all armory spots and nothing bugged out for us, can not reproduce bug

**Comment by Daemon53** [comment]
@kschreck0105 Can you reproduce this?

**Comment by kschreck0105** [comment]
I haven’t been able to. I will try again though

**Comment by Daemon53** [comment]
I'm ready to close this out if no one can duplicate

**Comment by kschreck0105** [comment]
Close it at this point. I haven’t been able to recreate either. 
if it happens again I will make the people it Al happens to attempt to recreate lol
