### ISSUE TITLE
Duckie Kitty Cat Cafe Toy No Icon

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#295]
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/c801df2a-9801-4f8b-bb2e-7a20d206705f)

I can put one together - just putting this as a reminder to me
for me to use to format later
https://media.tenor.com/WBJVPXhl0gMAAAAC/duck-cute.gif

**Comment by shelby0341** [comment]
Link to completed icon
https://drive.google.com/file/d/1c5DlMgGRB78JgG-ZlnPRHdIlQgAn-4q4/view?usp=drive_link

**Comment by shelby0341** [comment]
@Daemon53 this is ready

**Comment by shelby0341** [comment]
Duckie Kitty still broken :[

![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/25d15bec-3b37-49c5-82ae-eb3b8732902d)

**Comment by IngleArf** [comment]
![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/106269071/9b3e98c0-2ba8-4a6f-9f46-52659bd08365)

image fixed moving to closed

**Comment by shelby0341** [comment]
I just got this from a sushi box I ate lol

![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/2a281d68-8b65-4b13-a648-6cf294137c9d)

**Comment by IngleArf** [comment]
Once we actually push the changes that are stacked up it'll fix lol

**Comment by shelby0341** [comment]
Sorry I thought it was kekw
