### ISSUE TITLE
Treasure bottle & chest empty & chest bug

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#332]
Discord ticket: https://discord.com/channels/975465175178153994/1157412407317114991

"i opened a treasure bottle and the map poofed. there was a little treasure map icon in the bottom of my screen and when i opened my inventory it wasnt there"

"i opened a chest and it was empty"

"once you use the map and interact with the chest you get a "not accessable" error and cant get in your inventory until you take a nap. its happened twice and ive only done 2"

item in loot pool that's not an actual item: "actualbrain"

**Comment by IngleArf** [comment]
added captain skull

**Comment by IngleArf** [comment]
didnt test the chest yet, just fixed the fact that actual brain isnt in the game at all, and we needed a high drop item, and it was already buyable in pawn anyways

**Comment by IngleArf** [comment]
this chest error is extremely repeatable if they do the treasure map mini quest, unfortunately that part of the script is locked
