### ISSUE TITLE
Construction ped stops talking to you

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#334]
Silas is reporting after a random amount of times he does construction, the local will stop offering him jobs. He said he's done it for hours just fine, but sometimes it'll happen only after 3 jobs. If he changes his job to LSC and changes back, still won't talk to him. He has to fly out and back in for him to offer jobs again. He got this F8 error:
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/29f447e1-e2ee-457c-a372-7fc1c0320c21)

**Comment by shelby0341** [comment]
Also he said it's only happened to him at the top level he is now, it doesn't happen to Chief ever and he's a level below, and it's never happened in other tiers

**Comment by shelby0341** [comment]
https://medal.tv/games/gta-v/clips/1xMDNgePrkfUSb/d1337ErcCUtM?invite=cr-MSxjczMsMjIxNTQ0MzAs

**Comment by Daemon53** [comment]
Looks like it is clearing blips from level 1 places there. Doesn't seem to be checking what level they currently are. How does this ever work?

**Comment by shelby0341** [comment]
Silas said he did 10-12 runs and everything was good! Moving to complete
