### ISSUE TITLE
Pond Recipes - Maybe Fixed?

### ISSUE THREAD

**Issue by Daemon53** [DSRP-Inc/DSRP_Tickets#36]
Recipies  at the Pond Cafe   Garlic Bread Recipe gives you Chicken Wings
Olive Snack Recipe gives you bread sticks
Spaghetti Recipe doesn't take the ingredients from your inventory nor does it give the crafted Item
Couldn't try the Pizza Rolls need Tortillas

Orange juice recipe is the same as the spaghetti.  says ingredients are taken but they stay in inventory and no glass of orange juice is given

peach tea recipe requires tea, ice, water and peaches 
the recipe doesnt reflect that

Olive Snack crafts now but says Garlic Bread
just a suggestion but maybe one of the typing emotes for the cutting board craft station

**Comment by IngleArf** [comment]
These are complete
