### ISSUE TITLE
1 of 1 Car Adjustments

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#364]
Discord ticket: https://discord.com/channels/975465175178153994/1161567066705383424

Begae Ducrim (akwarlock) Supra engine sound is completely silent, you only hear it backfiring. There is no idle sound or sound when driving. She said she was okay with the stock sound if the custom sound wasn't going to work.

**Comment by shelby0341** [comment]
Make the Camaro for ayowhoisyou/nightraven/michael montana...quieter

**Comment by IngleArf** [comment]
Supra is fixed

**Comment by shelby0341** [comment]
Pagani Imola
![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/1c648830-219a-4c2e-a069-1b0beeb28f04)

**Comment by IngleArf** [comment]
Camaro volume issue seems to be fixed, had to convert one of the engine sound files to xml in codewalker and change some volume settings

**Comment by shelby0341** [comment]
The "celgt4" tops out at 100 fully upgraded, should be around 125-130 or so

**Comment by IngleArf** [comment]
celica has been fixed

**Comment by shelby0341** [comment]
dre's viper nitrous purge comes from...a ghost? lmfao. if the nitrous purge could be moved to under the windshield/above the hood by the windshield wipers area

![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/5c08560b-671b-43a5-90b8-e398f4476f12)

**Comment by shelby0341** [comment]
Dre's F1 that he's giving away, you get in it really weird. Your person just walks into the car for a while, stumbles sometimes, doesn't open the door and just appears in the car eventually.

**Comment by shelby0341** [comment]
going to close this since we're getting rid of these, the major issues were taken care of
