### ISSUE TITLE
Cat Cafe & Little Teapot tea trade?

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#371]
Little Teapot is requesting the three teas, Mint Tea, Jasmine Tea and Matcha Latte be moved from Cat Cafe to Little Teapot? Said he's willing to trade a couple coffees. But as it being called "Little Teapot" it only has two teas, the English Breakfast Tea and the Chai Latte.

Currently, Little Teapot has 2 teas, 6 coffees and 1 hot chocolate = 9 drinks total
Cat Cafe has 3 teas, 3 coffees, 6 bobas and 2 smoothies = 14 drinks total

For any reference:
Little Teapot has 18 food items = 27 total items
Cat Cafe has 11 food items = 25 total items

**Comment by IngleArf** [comment]
mint, jasmine, matcha drinks moved to teapot

**Comment by IngleArf** [comment]
items craftable and working moving to completed, advised cat cafe staff to come up with smoothies to add to menu to fill gap
