### ISSUE TITLE
House robberies - same interior bug

### ISSUE THREAD

**Issue by ssarahkathleeen** [DSRP-Inc/DSRP_Tickets#374]
Discord ticket #0219

Reported by: James Jameson (bliixxx)
Issue:
I was doing some house robberies this morning and i got 3 with the same interior. The first house i hit i was able to take everything and put it in the trunk like normal. the second 2 that were different houses in different areas but the same interior would not let me take TV, tapeplayer, coffee maker, art, ect. things you need to pick up and put in the trunk. I was thinking those specific items are tied together possibly per interior not job. 

no f8 error i saw and it gave me the promp to take them and just didnt do anything.
another person went in as well to see if they could take them and they werent able to either.

It seems like if you get the same interior it happens.
Different houses but the same interior model. I know me and Johnny ran some robberies over the weekend and it happened to him as well. I didn’t think of getting a clip. Molly also experienced this with me the first time it happened she wasn’t able to pick them up either.

I do know house interiors on the backend a little bit and they have always been and always will be the worst thing to script and work on from my experience in the past. So when it happened I assumed that those items are linked to the interiors themselves possibly if that’s some insight to help your testing!!

Sarah's notes: I know this has been an issue in a previous server where the interior's were repeated, so entered one house - cleared it out, entered the next one and you were technically entering the same interior so there was nothing to collect.

**Comment by IngleArf** [comment]
timer to reset houses set to 35 minutes, should help alleviate the issue at least a little bit, was previously set to 2 hours
