### ISSUE TITLE
Player in F8?

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#376]
I'm not sure what even caused this aside from opening the admin menu but it has an error with Krim Wunderlich? I know he's had a one off issue before with waste management job where he randomly doesn't get the keys to the garbage trucks still. I wasn't sure if he was scuffed in some way and this might lead to something?

![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/ff2d0991-3c1d-4771-a345-53e24ba5f7df)

**Comment by IngleArf** [comment]
this was likely the admin menu printing his info for some reason, will keep an eye open to see if it happens at all anymore, but there have been a couple admin menu updates since
