### ISSUE TITLE
Car deleted from database

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#377]
My R34 Skyline got scuffy trying to change the plate before garaging it. Now it's giving me the error of not owning the vehicle but owning it. I was able to spawn a different one and garage it and pull it out just fine.

So, the Nissan GTR 34 with the plate "MOIST" should be removed from the database. I can't dvdb it because it says it's not a player owned vehicle.
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/667f6fbc-1e37-44fd-a6f9-20aa50a7450b)

**Comment by shelby0341** [comment]
Seen that the scuffed one was deleted, went to change the R34 that was able to be restored to the MOIST plate and uhh, now I can't store it, says its not mine. Try to admincar it, says I already own it.

![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/0fdaec00-c506-475e-8949-a86517730b14)
![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/49e26ba2-4c4d-4e8e-9ef9-ecce6c34d50b)
![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/06061aea-942f-4b96-9f2e-e3fa016a4801)

**Comment by IngleArf** [comment]
this was straight scruffed, manually deleted car from DB and replaced it
