### ISSUE TITLE
Emotes not cancelling on pressing "E"

### ISSUE THREAD

**Issue by kschreck0105** [DSRP-Inc/DSRP_Tickets#38]
**Reference ticket number:**

**Reporting persons Discord name:**
Rogue205(aladrex yelled at me again)

**Clearly describe the bug:**
while leaning and sitting in chairs, pressing X doesnt cancel out the emote

**Describe the steps to reproduce:**
do t e/lean and then press "X"

**What is the expected behavior?**
cancel out of emote and be able to walk around

**Screenshots/clips:**

**Comment by IngleArf** [comment]
Sitting in chairs exit key is "E" @Daemon53

**Comment by IngleArf** [comment]
Just tested this and it is functional. Will test further before closing ticket

**Comment by IngleArf** [comment]
Can not reproduce after another test will close this ticket and monitor situation
