### ISSUE TITLE
MDT Allows you to change radio station

### ISSUE THREAD

**Issue by Daemon53** [DSRP-Inc/DSRP_Tickets#41]

**Comment by shelby0341** [comment]
@Daemon53 where was this at in MDT?

**Comment by Daemon53** [comment]
lol, must have worked if you can't find it! You use to right click on a person in the mdt to set radio

**Comment by Daemon53** [comment]
We just got rid of it all together and are going to implement a slash command for personal radio use. @shelby0341

**Comment by shelby0341** [comment]
can confirm the option is no longer in MDT, moving to completed
