### ISSUE TITLE
Brynjar's Item

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#410]
https://discord.com/channels/975465175178153994/1168926981014966406

**Comment by shelby0341** [comment]
https://drive.google.com/file/d/15HKLwwllHfqnqOlMGSBO6eldaXedXcYt/view?usp=drive_link

**Comment by shelby0341** [comment]
Name: Mark of Eir

Description: A flattened and highly polished 5.56 casing etched with symbols. The primary rune appears to be an M and R joined together, surrounded by other runes in a precise circle. It carries a comforting warmth and is oddly weighty for its size.

On Use: /e meditate

**Comment by Daemon53** [comment]
- Third eye just for his CID
- Takes one pistol_ammo from ammunation and makes 12 pressed bullet casings
- Item description
- On use of item, do /e meditate

**Comment by Daemon53** [comment]
BoxZone:Create(vector3(94.91, 3753.42, 41.31), 0.55, 0.7, {
  name = "bryn",
  heading = 70,
  --debugPoly = true,
  minZ = 40.51,
  maxZ = 41.81

**Comment by shelby0341** [comment]
He's happy with his item, moving to complete
