### ISSUE TITLE
EMS Rank Renames

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#413]
Can EMS grade 9, 8 and 6 please be renamed to the following:

Grade 9: Medical Director -> SAMS Director
Grade 8: Director of Operations -> Division Director
Grade 6: OP. Supervisor -> OP. Coordinator

![Screen Shot 2023-11-06 at 10 26 51 AM](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/45bff53a-9608-436c-ba94-f370be9c09db)

**Comment by IngleArf** [comment]
completed
