### ISSUE TITLE
Pond Cafe Food

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#420]
Add food recipes (I'll add links to the icons in another comment later)

Blueberry Lemonade - requires at least blueberries and lemons to make
Iced Cinnamon Mocha - requires at least coffee beans, cinnamon and chocolate
Struffoli - requires at least honey and vanilla
Fried Mac and Cheese - ?

With the fried mac and cheese addition, they're requesting that 'pasta' be added to common ingredients, along with strawberries.

**Comment by shelby0341** [comment]
Icons:
https://drive.google.com/drive/folders/18LoAIK43uMv_ddLkt1GdQgmvzT31Ipim?usp=drive_link

**Comment by IngleArf** [comment]
added and tested, pushed to live for restart
