### ISSUE TITLE
LSC Garage Move Forward

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#470]
Currently, larger vehicles like trucks tend to spawn on the cement wall when you pull them out of the garage, can send them in the air and on the other side of the wall.
Seems like the spawn point for the garage for vehicle could stand to be moved forward some

**Comment by Daemon53** [comment]
If you want to spawn a car, move it forward a little and give me the new coordinates, I can throw that in pretty quick.

**Comment by shelby0341** [comment]
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/8ad6f66f-0694-42c8-a266-2e9f6891e3d8)
