### ISSUE TITLE
PD Heli Camera Not working

### ISSUE THREAD

**Issue by kschreck0105** [DSRP-Inc/DSRP_Tickets#48]
**Reference ticket number:**

**Reporting persons Discord name:**
Rogue205

**Clearly describe the bug:**
Camera in PD Helicopter is not working. 

**Describe the steps to reproduce:**
Get in PD Heli from MRPD and take off. press E (Default bind)  and you should see camera popup

**What is the expected behavior?**
goes into the camera mode

**Screenshots/clips:**

**Comment by Daemon53** [comment]
Working

**Comment by shelby0341** [comment]
Can confirm is working as intended, moving to completed
