### ISSUE TITLE
Small Icon for Store Robbery

### ISSUE THREAD

**Issue by Daemon53** [DSRP-Inc/DSRP_Tickets#50]

**Comment by kschreck0105** [comment]
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/68434249/c03df796-c814-48cf-b524-b14cb4203bf0)

**Comment by PINCH97** [comment]
Increased size

**Comment by kschreck0105** [comment]
![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/68434249/99df1247-b549-4126-a292-5c1886a7195f)

Coming up as this at current of this post

**Comment by kschreck0105** [comment]
![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/68434249/1443b764-6e63-439b-bb55-817d84beeb5c)

This is the escape button map

**Comment by PINCH97** [comment]
@kschreck0105 Sorry Actually fixed now :D
