### ISSUE TITLE
Give Cash & Cash Register Names Change to ID Numbers

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#69]
**Is your feature request related to a problem? Please describe.**
It could become a problem for some. When you use the "cashgive" or to charge someone via the cash register, it displays the names of people around you. Which can then also not only display an admin in the area watching someone, but can hinder someones RP if they are maybe a cop going undercover or trying to lay low from something, that makes every transaction become not-anonymous. Even if you are trying to do something with cash to not have it on the banks, the person will see their name when they give cash. People also like to use this to meta.

**Describe the solution you'd like**
A great solution to this is if we could just use the persons ID number, NOT their name. Ask for their "PayPal" or "lucky number" whatever you want to call it, instead. It makes things more private.

**Comment by Daemon53** [comment]
@shelby0341 Can you test this? We turned down the radius on it. Try spectating and see if it shows up.

**Comment by shelby0341** [comment]
Geevum tried using /cashregister when I was /admin > spectating him, and he could see me as 2m away. I had him try again when i /admin insivible and noclip, and my name would still come up on the /cashregister.
It also still says the characters names and not just their ID's.

**Comment by Daemon53** [comment]
@IngleArf

**Comment by shelby0341** [comment]
Also just as a side note, you have to be less than 5m from the person to charge them via /cashregister, and this is what that looks like distance wise just for reference which I think is fair


![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/03b23ae8-4bdd-43fb-88e9-df6d7d7de301)
