### ISSUE TITLE
Yoga Mat Disappearing

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#7]
**Reference ticket number:**

**Reporting persons Discord name:**
shelby0341

**Clearly describe the bug:**
When you put down a yoga mat from the leisure store, it just goes through the ground. Takes it from your inventory but there's nothing there.

**Describe the steps to reproduce:**
Buy a yoga mat, "use" it from inventory

**What is the expected behavior?**
To be able to actually use the yoga mat and see it on the ground

**Screenshots/clips:**

**Comment by IngleArf** [comment]
fixed. and tested.

switched to 3rd eye system for entire operation
