### ISSUE TITLE
Pictures on Phones

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#70]
**Reference ticket number:**

**Reporting persons Discord name:**
shelby0341

**Clearly describe the bug:**
When you try to take a photo to send to someone, it just shows up as broken photos, see screenshot below.

**Describe the steps to reproduce:**
Try to send a picture vis SMS

**What is the expected behavior?**
To actually see the photos

**Screenshots/clips:**
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/3d57ab54-3390-434b-814d-5d52eee18193)

**Comment by Daemon53** [comment]
Cannot reproduce

**Comment by kschreck0105** [comment]
cannot reproduce either

**Comment by shelby0341** [comment]
Hopefully just a one off, just odd we both seen it that way. Thank you!

**Comment by ssarahkathleeen** [comment]
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/141734142/c5f67651-0a3c-4d23-869d-c32d8c104738)

tried it as well, didn't happen to me

**Comment by ssarahkathleeen** [comment]
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/141734142/3fdaf2d0-8ca1-4cba-bb13-5bb41f27bb7f)
tested it and couldn't reproduce it either
