### ISSUE TITLE
Clothing

### ISSUE THREAD

**Issue by Daemon53** [DSRP-Inc/DSRP_Tickets#72]
Go through EUP and delete the following (got numbers from raynor)
Body armor 69 texture 2
Body armor 69 texture 4
Body Armor 68 Texture 2
Body Armor 68 Texture 3
Body Armor 68 Texture 4
Hat 152 Texture 0
Hat 151 Texture 0

Those are custom made pd clothing for people who are not PD from another place

**Comment by IngleArf** [comment]
Need to come up with a solution for logos on ocean clothing otherwise this is complete

**Comment by shelby0341** [comment]
I'm going to mark this one as complete and start an EMS one as there's several things to go over with it. Cleaning up the testing issues so it's known that it's not worked on yet.
