### ISSUE TITLE
Add quick draw to holster clothing

### ISSUE THREAD

**Issue by Daemon53** [DSRP-Inc/DSRP_Tickets#76]

**Comment by IngleArf** [comment]
added holster variations from clothing packs

**Comment by IngleArf** [comment]
added holster. Works for males

**Comment by shelby0341** [comment]
female scarf/chain #175, 180, 182, 189, 190, 191, 192, 193, 194, 195, 196, 197 do not quick draw. I tried going on PD duty, logging in and out of the server.
181 seems to be the only one that DOES work

**Comment by IngleArf** [comment]
This should work now. i tested a random group, the numbers have changed due to the change in game versions

**Comment by shelby0341** [comment]
All holsters seem to be working as intended, moving to completed
