### ISSUE TITLE
MDT Profiles not able to be selected/edited

### ISSUE THREAD

**Issue by kschreck0105** [DSRP-Inc/DSRP_Tickets#8]
**Reference ticket number:**

**Reporting persons Discord name:**
Rogue205

**Clearly describe the bug:**
Police MDT Profiles not able to be selected

**Describe the steps to reproduce:**
Look up person in MDT and you can see the search but unable to select the profile to make changes

**What is the expected behavior?**
after searching the profile i am able to select the person in question and edit the profile.

**Screenshots/clips:**
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/68434249/19941084-5ab5-4d88-9036-812327116dce)

**Comment by Daemon53** [comment]
Fixed


![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/5520538/fdc3eb71-9f7d-4102-8104-1baa7956dca3)

**Comment by kschreck0105** [comment]
can confirm profiles are about to be searched, edited and saved on PD MDT

**Comment by kschreck0105** [comment]
while in icidents, under criminals involved, you cannot search by last name. 

Not a deal breaker, but would be nice to be able...

For example if i search for rayner it wont come up with anything
if i search for kyle r it will come up with me.

**Comment by Daemon53** [comment]
@kschreck0105 Yes, that's in the enhancements for PD for Post Launch
