### ISSUE TITLE
BBQ

### ISSUE THREAD

**Issue by Daemon53** [DSRP-Inc/DSRP_Tickets#84]
- [x] look into where to sell raw food items
- [x] set prices for raw food items
- [x] add food items to jim-consumables and add values

**Comment by IngleArf** [comment]
Sold At Leisure Shop
Set Prices for Raw ITems in Leisure Shop
Set Values in Consumables 

4-5 dogs or burgers will fill you up
prices are 30 dollars to craft a single hot dog
and 55 to craft a burger 
this brings the average cost to fully fill your hunger to around -200ish to totally fill up on burgers or hotdogs...and also, people tend to eat a bunch of food at a bbq anyway right

**Comment by IngleArf** [comment]
tested and working
