### ISSUE TITLE
Shotgun Ammo not working with shotguns

### ISSUE THREAD

**Issue by kschreck0105** [DSRP-Inc/DSRP_Tickets#9]
**Reference ticket number:**

**Reporting persons Discord name:**
Rogue205

**Clearly describe the bug:**
When holding shotgun and tryuing

**Describe the steps to reproduce:**
get shot gun and get shotgun ammo and attempt to reload said shotgun

**What is the expected behavior?**
i use shotgun ammo and goes into reload animation and weapon is reloaded

**Screenshots/clips:**
![image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/68434249/8bd70f04-2339-4d94-b695-4c366ff7acfa)

**Comment by kschreck0105** [comment]
Might be working now...

**Comment by kschreck0105** [comment]
this was working today(sunday)

**Comment by PINCH97** [comment]
Issue was resolved when I fixed the hunting rifle ammo was a conflict with the code which I changed.
